USE [master]
GO

/****** Object:  Database [Veterinaria]    Script Date: 8/10/2024 22:39:29 ******/
CREATE DATABASE [Veterinaria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Veterinaria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Veterinaria.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Veterinaria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Veterinaria_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Veterinaria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Veterinaria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Veterinaria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Veterinaria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Veterinaria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Veterinaria] SET ARITHABORT OFF 
GO

ALTER DATABASE [Veterinaria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Veterinaria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Veterinaria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Veterinaria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Veterinaria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Veterinaria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Veterinaria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Veterinaria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Veterinaria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Veterinaria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Veterinaria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Veterinaria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Veterinaria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Veterinaria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Veterinaria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Veterinaria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Veterinaria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Veterinaria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Veterinaria] SET  MULTI_USER 
GO

ALTER DATABASE [Veterinaria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Veterinaria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Veterinaria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Veterinaria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Veterinaria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Veterinaria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Veterinaria] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Veterinaria] SET  READ_WRITE 
GO

